### ISSUE TITLE
this is a nice project, can it surport for dotnet core 3.1 ?

### ISSUE THREAD

**Issue by robyle** [Marfusios/crypto-watcher#1]
excuse me ,my product runtime is on dotnet core 3.1. how can test run this project ?

**Comment by Marfusios** [comment]
Hi @robyle, 

there shouldn't be any issue, because dependencies support also `netstandard2.0`. 
So the only step is to update `<TargetFramework>` in [csproj file](https://github.com/Marfusios/crypto-watcher/blob/main/CryptoWatcher.csproj#L5) and compile the application.

**Comment by robyle** [comment]
yeah,  I try modify it ,but it get a error for C# language version.   after .net 5.0 ,We must to use C# 9.0，but .net core 3.1 just surpport last to C# 8.0.

**Comment by Marfusios** [comment]
I see, you probably need to change some code to avoid new C# features. 
Post compiler errors here if you are unsure how to fix them.

**Comment by robyle** [comment]
> I see, you probably need to change some code to avoid new C# features.
> Post compiler errors here if you are unsure how to fix them.

yeah，Thanks reply to me. I fix it. and normaly to run on .NET Core 3.1.
